### ISSUE TITLE
Kontaktní formulář se odešle až při refreshi stránky

### ISSUE THREAD

**Issue by homoky** [retailtrek/payplatinum-cz#16]
Implementoval jsem uplně simple kontaktní formulář pomocí formspree, který jsem napojil na ten váš nakodovaný formulář.

Funguje to korektně ve všech prohlížečích.

V IE11 to nefungovalo do doby, kdy <input submit neměl name a value parametr (bug IE11). 

Formulář se teď odešle ve chvíli, kdy na stránku přijdu po refreshi. Tzn. jsem na stránce, dám refresh -> odešle se.

Pokud jsem na homepage, v navigaci kliknu na kontakt, tak se to neodešle. Musím znovu udělat refresh , pak to jde.

Tento bug je pouze v IE11. 

Poprosím o pomoc a opravu. Potom s Petrem domluvíme předání díla. Zbytek je za mě funkční a ready k předání.

**Comment by katzino** [comment]
Prosim o kontrolu, problem byl u buttonu, kteremu se z fely predavaji vsechny props a IE11 z nejakeho neznameho duvodu akceptuje jenom name a value.

**Comment by homoky** [comment]
Super. Díky.
